export const cardItems = [
  {
    id: 1,
    title: "Fundamentos Next.JS #04",
    channel: "Next JS Official",
    views: "107 mil visualizações",
    time: "há 2 horas",
  },
  {
    id: 2,
    title: "Navegando entre páginas #03",
    channel: "Next JS Official",
    views: "88 mil visualizações",
    time: "há 5 horas",
  },
  {
    id: 3,
    title: "Integrando com API #03",
    channel: "Next JS Official",
    views: "23 mil visualizações",
    time: "há 23 dias",
  },
  {
    id: 4,
    title: "Estratégias de renderização #03",
    channel: "Next JS Official",
    views: "98 mil visualizações",
    time: "há 1 meses",
  },
  {
    id: 5,
    title: "Rotas #03",
    channel: "Next JS Official",
    views: "11 mil visualizações",
    time: "há 3 meses",
  },
  {
    id: 6,
    title: "Fundamentos Next.JS #03",
    channel: "Next JS Official",
    views: "107 mil visualizações",
    time: "há 3 meses",
  },
  {
    id: 7,
    title: "Navegando entre páginas #02",
    channel: "Next JS Official",
    views: "88 mil visualizações",
    time: "há 4 meses",
  },
  {
    id: 8,
    title: "Integrando com API #02",
    channel: "Next JS Official",
    views: "23 mil visualizações",
    time: "há 5 meses", 
  },
  {
    id: 9,
    title: "Estratégias de renderização #02",
    channel: "Next JS Official",
    views: "98 mil visualizações",
    time: "há 10 meses",
  },
  {
    id: 10,
    title: "Rotas #02",
    channel: "Next JS Official",
    views: "11 mil visualizações",
    time: "há 11 meses",
    
  },
  {
    id: 11,
    title: "Fundamentos Next.JS #02",
    channel: "Next JS Official",
    views: "107 mil visualizações",
    time: "há 1 ano",
  },
  {
    id: 12,
    title: "Navegando entre páginas #01",
    channel: "Next JS Official",
    views: "88 mil visualizações",
    time: "há 1 ano",
  },
  {
    id: 13,
    title: "Integrando com API #01",
    channel: "Next JS Official",
    views: "23 mil visualizações",
    time: "há 1 ano",
  },
  {
    id: 14,
    title: "Estratégias de renderização #01",
    channel: "Next JS Official",
    views: "98 mil visualizações",
    time: "há 2 anos",
  },
  {
    id: 15,
    title: "Rotas #01",
    channel: "Next JS Official",
    views: "11 mil visualizações",
    time: "há 2 anos",
  },
  {
    id: 16,
    title: "Fundamentos de Next.JS #01",
    channel: "Next JS Official",
    views: "11 mil visualizações",
    time: "há 3 anos",
  },
]